### ISSUE TITLE
Compile to JS before publishing npm

### ISSUE THREAD

**Issue by Eibwen** [KirillTemnov/node-pocket#1]
Of the npm's for pocket that i'm finding, yours seems to follow the most node standards, but the npm package does not contain js, so its giving me an error when i try to use it in a non-coffeescript project.
You can fix this as described below:

http://stackoverflow.com/a/13646337/356218

https://github.com/assaf/zombie/blob/master/package.json#L40

**Comment by Eibwen** [comment]
The work-around for that is to:

```
npm install -g coffee-script
coffee -c node_modules\node-pocket\index.coffee
```

on every computer the script using this as a dependency is installed on.

Please also add https://docs.npmjs.com/files/package.json#repository to your package.json, so the link is easier to find on npmjs.com

**Comment by KirillTemnov** [comment]
Hi @Eibwen !
I've make these changes in next couple days.
Need to check out,  how it works on new node.js.

**Comment by KirillTemnov** [comment]
@Eibwen can you check the new version 0.9.5?

It installs `CoffeeScript` globaly and compile files to js.
But it may cause issues if you can't write to `/usr/bin` and `/usr/lib/node_modules/`.
